name: Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ['9.0.2']
        cabal: ['3.6.2.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: |
        cabal freeze
    - name: Cache cabal
      uses: actions/cache@v2
      id: cache-cabal
      with:
        path: 'C:\sr'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('D:\a\tidal-gui\tidal-gui\src\') }}-a
        
    - name: Cache dist
      uses: actions/cache@v2
      id: cache-bin
      with:
        path: 'D:\a\tidal-gui\tidal-gui\dist-newstyle\'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('D:\a\tidal-gui\tidal-gui\src\') }}-b
    
    - name: cabal build
      run: cabal v2-build --enable-tests
      
    - name: remove unneccessary libs 
      run: | 
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\Cabal-*' -Recurse
  #          Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\rts-*' -Recurse
            
    - name: move GHC libs and configs
      run: |
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\' -Recurse -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\ghc-packages'
            Move-Item -Path 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\ghc-packages\settings' -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\settings'
            Move-Item -Path 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\ghc-packages\platformConstants' -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\platformConstants'
            Move-Item -Path 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\ghc-packages\llvm-passes' -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\llvm-passes'
            Move-Item -Path 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\ghc-packages\llvm-targets' -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\llvm-targets'
            
    - name: move mingw
      run: Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\mingw\' -Recurse -Destination 'D:\a\tidal-gui\tidal-gui\binary\mingw'
            
            
    - name: move installed packages
      run: Copy-Item -Path 'C:\sr\ghc-${{ matrix.ghc }}\' -Recurse -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\packages'
   
    - name: change paths in config files (packages)
      run: |
            Move-Item -Path 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\packages\package.db\' -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.db\'
            $configs = Get-ChildItem 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.db\' -Recurse
            $configs | %{ (gc $_) -replace "C:\\sr\\ghc-${{ matrix.ghc }}", '$topdir\packages' | Set-Content $_.fullname}
   
    - name: move ghc package config
      run: |
            Move-Item -Path 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\ghc-packages\package.conf.d\' -Destination 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.conf.d\'
            $configs = Get-ChildItem 'D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.conf.d\' -Recurse
            $configs | %{ (gc $_) -replace "${pkgroot}", '${pkgroot}\ghc-packages' | Set-Content $_.fullname}
   
    - name: ghc-pkg recache
      run: | 
            $ENV:GHC_PACKAGE_PATH="D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.conf.d;D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.db"
            ghc-pkg -v2 recache --package-db="D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.conf.d"
            ghc-pkg -v2 recache --package-db="D:\a\tidal-gui\tidal-gui\binary\haskell-libs\package.db"

   
    - name: move executable
      run: Copy-Item -Path 'D:\a\tidal-gui\tidal-gui\dist-newstyle\build\x86_64-windows\ghc-${{ matrix.ghc }}\tidal-gui-0.1.0.0\x\tidal-gui\build\tidal-gui\tidal-gui.exe' -Recurse -Destination 'D:\a\tidal-gui\tidal-gui\binary\tidal-gui.exe'
    
    - name: move static
      run: Copy-Item -Path 'D:\a\tidal-gui\tidal-gui\static\' -Recurse -Destination 'D:\a\tidal-gui\tidal-gui\binary\static'
    
    - name: zip files
      run: Compress-Archive -LiteralPath 'D:\a\tidal-gui\tidal-gui\binary\' -DestinationPath 'D:\a\tidal-gui\tidal-gui\tidal-windows.zip'

    - name: Release
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 'D:\a\tidal-gui\tidal-gui\tidal-windows.zip'
        tag_name: 5
   
   # - name: setup node
   #   uses: actions/setup-node@v3
   #   with:
   #      node-version: 16
    
   # - name: electron forge
   #   run: |
   #         npm install --save-dev @electron-forge/cli
   #         npx electron-forge import
   #         npm run make
      
   # - name: Release
   #   uses: softprops/action-gh-release@v1
   #   with:
   #       files: |
   #               out\make\squirrel.windows\x64\*.exe
   #               out\make\squirrel.windows\x64\*.nupkg
